services:
  postgres:
    container_name: lovableDB
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: lovableDB
      POSTGRES_PASSWORD: password

volumes:
  postgres_data: